export const cards = [
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '340608',
        name: 'Tripti Ghar',
        uuid: '7431aacc-584f-4eb3-a7ef-d7f6a0bb5c4e',
        city: '7',
        area: 'Anandapuri',
        totalRatingsString: '',
        cloudinaryImageId: 'pru93po3woiea7otwczd',
        cuisines: ['Biryani', 'Indian', 'Chinese'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: '39 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'tripti-ghar-barrackpore-barrackpore',
          city: 'Kolkata',
        },
        cityState: '7',
        address: '',
        locality: 'Barrackpore',
        parentId: 217843,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 7100,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 7100,
          message: '',
          title: 'Delivery Charge',
          amount: '7100',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=7630640~p=1~eid=00000189-ce87-29b7-1a3d-ab1100a1016f~srvts=1691387111863~83647',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '7.8 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=340608&source=collection&query=Chinese',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 0,
          lastMileDistance: 7.8,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '3.9',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '94439',
        name: 'Punjab Restaurant and Madras Tiffin',
        uuid: '2b12d856-6905-4b35-8dac-eed36693c0d9',
        city: '7',
        area: 'Barrackpore',
        totalRatingsString: '',
        cloudinaryImageId: 'fyueovejjechcyzli5xt',
        cuisines: ['Indian', 'Chinese'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 51,
        minDeliveryTime: 51,
        maxDeliveryTime: 51,
        slaString: '51 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant:
            'punjab-restaurant-and-madras-tiffin-other-dummy-inbound-area',
          city: 'Kolkata',
        },
        cityState: '7',
        address: '',
        locality: 'S N BANERJEE ROAD, GUPTA COMPLEX, BARRACKPORE',
        parentId: 162044,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 7100,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 7100,
          message: '',
          title: 'Delivery Charge',
          amount: '7100',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=7630389~p=2~eid=00000189-ce87-29b7-1a3d-ab1200a1023c~srvts=1691387111863~83647',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '8 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=94439&source=collection&query=Chinese',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 51,
          minDeliveryTime: 51,
          maxDeliveryTime: 51,
          lastMileTravel: 0,
          lastMileDistance: 8,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.2',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '149296',
        name: 'Dream Bar & Restaurant',
        uuid: '48db99a3-f403-42fe-bff1-498e6c2f777c',
        city: '7',
        area: 'Anandapuri',
        totalRatingsString: '',
        cloudinaryImageId: 's8vjuan3y9u45m294vrz',
        cuisines: ['North Indian', 'Chinese'],
        tags: [],
        costForTwo: 60000,
        costForTwoString: '₹600 FOR TWO',
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: '43 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'dream-bar-restaurant-barrackpore-barrackpore',
          city: 'Kolkata',
        },
        cityState: '7',
        address: '',
        locality: 'Barrackpore',
        parentId: 74734,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 8600,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 8600,
          message: '',
          title: 'Delivery Charge',
          amount: '8600',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '8.5 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=149296&source=collection&query=Chinese',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 0,
          lastMileDistance: 8.5,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '386277',
        name: 'Bread N Butter',
        uuid: 'b7eab686-2f65-4374-957a-3c1199d60451',
        city: '7',
        area: 'Barrackpore',
        totalRatingsString: '',
        cloudinaryImageId: 'jzcd1ys0n4dtvrcgiahx',
        cuisines: ['Continental', 'Chinese', 'Fast Food'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 53,
        minDeliveryTime: 53,
        maxDeliveryTime: 53,
        slaString: '53 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'bread-n-butter-barrackpore-barrackpore',
          city: 'Kolkata',
        },
        cityState: '7',
        address: '',
        locality: 'Sn Banerjee Rd',
        parentId: 49713,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 7100,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 7100,
          message: '',
          title: 'Delivery Charge',
          amount: '7100',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '8 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=386277&source=collection&query=Chinese',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 53,
          minDeliveryTime: 53,
          maxDeliveryTime: 53,
          lastMileTravel: 0,
          lastMileDistance: 8,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
];
